"""
edge_dashboard.py
-----------------
Streamlit dashboard for visualizing Edge Intelligence outputs.

It reads the latest log file generated by `edge_executor.py`,
parses the execution details, and (optionally) plots numeric data
from generated tasks (like comfort index or anomalies).

Run:
    streamlit run edge_dashboard.py
"""

import os
import re
import pandas as pd
import streamlit as st
from datetime import datetime

LOG_DIR = "logs"
DATA_DIR = "data"
TASKS_DIR = "generated_tasks"

# === Utility functions ===
def get_latest_log():
    """Return path to the latest log file."""
    if not os.path.exists(LOG_DIR):
        return None
    files = [os.path.join(LOG_DIR, f) for f in os.listdir(LOG_DIR) if f.endswith(".log")]
    return max(files, key=os.path.getmtime) if files else None

def parse_log(filepath):
    """Parse log file for task results."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    task_blocks = re.split(r"={10,}", content)
    entries = []
    for block in task_blocks:
        if "Executing:" not in block:
            continue
        task_name = re.search(r"Executing:\s*(.+\.py)", block)
        status = re.search(r"Status:\s*(\w+)", block)
        duration = re.search(r"Duration:\s*([\d.]+)", block)
        output_match = re.search(r"Output:\n(.+?)(?=\n[-]{5,}|$)", block, re.S)

        entries.append({
            "task": task_name.group(1) if task_name else "Unknown",
            "status": status.group(1) if status else "Unknown",
            "duration_s": float(duration.group(1)) if duration else None,
            "output": output_match.group(1).strip() if output_match else ""
        })

    return pd.DataFrame(entries)

def detect_comfort_data(df):
    """Try to parse numeric outputs from the comfort index task, if present."""
    for _, row in df.iterrows():
        if "comfort_index" in row["task"]:
            try:
                temp_df = pd.read_csv(os.path.join(DATA_DIR, "sample_data.csv"))
                temp_df["comfort_index"] = pd.Series(
                    [float(x.split(",")[-1]) for x in row["output"].splitlines()[1:] if "," in x]
                )
                return temp_df
            except Exception:
                pass
    return None

# === Streamlit layout ===
st.set_page_config(page_title="Edge Intelligence Dashboard", layout="wide")
st.title("🧠 LLM-Assisted Edge Intelligence Dashboard")

log_file = get_latest_log()
if not log_file:
    st.warning("No log file found. Please run edge_executor.py first.")
    st.stop()

st.sidebar.header("Configuration")
st.sidebar.write(f"**Current Log File:** `{os.path.basename(log_file)}`")
refresh = st.sidebar.button("🔄 Refresh")

st.markdown(f"### Latest Edge Execution Log — *{datetime.fromtimestamp(os.path.getmtime(log_file)).strftime('%Y-%m-%d %H:%M:%S')}*")

df_log = parse_log(log_file)
if df_log.empty:
    st.error("No task entries found in the log file.")
    st.stop()

# === Summary statistics ===
col1, col2, col3 = st.columns(3)
col1.metric("Tasks Executed", len(df_log))
col2.metric("Successful Tasks", (df_log["status"] == "SUCCESS").sum())
col3.metric("Average Duration (s)", f"{df_log['duration_s'].mean():.2f}" if df_log['duration_s'].notna().any() else "N/A")

st.dataframe(df_log[["task", "status", "duration_s"]])

# === Detailed outputs ===
st.markdown("### 📋 Task Outputs")
for _, row in df_log.iterrows():
    with st.expander(f"{row['task']} — {row['status']} ({row['duration_s']:.2f}s)"):
        st.code(row["output"] or "No output captured.", language="text")

# === Visualization section ===
st.markdown("### 📊 Visual Insights")
comfort_data = detect_comfort_data(df_log)
if comfort_data is not None:
    st.line_chart(
        comfort_data,
        x="timestamp",
        y=["temperature_c", "humidity_percent", "comfort_index"],
        height=400
    )
else:
    st.info("No numeric comfort index data detected for plotting.")

st.caption("Data auto-refreshes when you re-run or click Refresh.")

if refresh:
    st.rerun()
