"""
llm_orchestrator.py
-------------------
This script reads sample environmental data, metadata, and context,
then asks an LLM (e.g., GPT-5) to generate multiple small Python
programs that can run on an edge device to extract insights.

Why adaptive?
------------
This version check if there is a list of tasks already generated. 
If so, it asks the LLM to only generate new list of task, if any. 
"""

import os
import json
from openai import OpenAI
from config import DATA_TYPE, OPENAI_API_KEY
from string import Template
from prompts.get_tasks_list_adaptive import SYSTEM_PROMPT
import sys

# Initialize the LLM client
client = OpenAI(api_key=OPENAI_API_KEY)

# Paths
#DATA_TYPE = "temp_humidity"
BASE_PATH = "data/"+DATA_TYPE+"/"
DATA_PATH = BASE_PATH+"sample_data.csv"
META_PATH = BASE_PATH+"metadata.json"
CONTEXT_PATH = BASE_PATH+"context.txt"
OUTPUT_DIR = "generated_tasks/"+DATA_TYPE
TASK_LIST_PATH = OUTPUT_DIR+"/tasks_list1.json"

# Read all inputs
with open(DATA_PATH, "r") as f:
    sample_data = f.read()

with open(META_PATH, "r") as f:
    metadata = json.load(f)

with open(CONTEXT_PATH, "r") as f:
    context = f.read()

with open(TASK_LIST_PATH, "r") as f:
    existing_tasks = f.read()

system_prompt = Template(SYSTEM_PROMPT).substitute(DATA_TYPE=DATA_TYPE)
# User prompt with data, metadata, and context
user_prompt = f"""
Sample Data:
{sample_data}

Metadata:
{json.dumps(metadata, indent=2)}

Context:
{context}

Existing tasks and their descriptions:
{existing_tasks}
"""

#print how many tasks are in existing_tasks
existing_tasks_json = json.loads(existing_tasks)
print(f"{len(existing_tasks_json['tasks'])} no. of existing tasks are sent to LLM.")

# Call the LLM
response = client.chat.completions.create(
    model="gpt-5",
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]    
)

# Extract response content
raw_output = response.choices[0].message.content

# Parse JSON safely
try:
    tasks_data = json.loads(raw_output)
except json.JSONDecodeError:
    print("The LLM response was not valid JSON. Saving raw output for review.")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(os.path.join(OUTPUT_DIR, "raw_output.txt"), "w") as f:
        f.write(raw_output)
    exit()

###
# {
#   "tasks": [],
#   "empty_reason": "<reason for not generating new tasks>"
# }
# if no new tasks are generated, print the reason
if len(tasks_data.get("tasks", [])) == 0:
    reason = tasks_data.get("empty_reason", "No reason provided.")
    print(" No new tasks were generated. Reason: " + reason)
    exit()

# print how many new tasks are generated
print(f"{len(tasks_data['tasks'])} new tasks are generated by LLM.")

# ensure each new task explicitly carries its DATA_TYPE for downstream modules
for t in tasks_data.get("tasks", []):
    t.setdefault("data_type", DATA_TYPE)

#save the new tasks to separate new_tasks.json file so that task_code_generator_update.py can use it to generate code files
os.makedirs(OUTPUT_DIR, exist_ok=True)
with open(os.path.join(OUTPUT_DIR, "new_tasks.json"), "w", encoding="utf-8") as f:
    json.dump(tasks_data, f, indent=2)

# TODO: if the json file exists, append the new tasks to existing tasks
if os.path.exists(TASK_LIST_PATH):
    with open(TASK_LIST_PATH, "r", encoding="utf-8") as f:
        existing_tasks_data = json.load(f)
    # Append new tasks
    existing_tasks_data["tasks"].extend(tasks_data["tasks"])
    tasks_data = existing_tasks_data

# write updated tasks_list1.json (tasks_data now contains merged list)
with open(os.path.join(OUTPUT_DIR, "tasks_list1.json"), "w", encoding="utf-8") as f:
    json.dump(tasks_data, f, indent=2)
print("The list of all tasks with their description are successfully saved in "+os.path.join(OUTPUT_DIR, "tasks_list1.json"))
### Now the json_task_list contains all newly tasks from llm_orchestrator_adaptive.py