"""
llm_orchestrator.py
-------------------
This script reads sample environmental data, metadata, and context,
then asks an LLM (e.g., GPT-5) to generate multiple small Python
programs that can run on an edge device to extract insights.

Why adaptive?
------------
This version check if there is a list of tasks already generated. 
If so, it asks the LLM to only generate new list of task, if any. 

Why resource?
------------
This is resource-aware version. It provides the LLM with current
resource usage summary of the edge device so that the LLM can decide
whether to generate new tasks or not based on the resource constraints.

last code updated on 15-11-2025
"""

import os
import json
from string import Template
from config import DATA_TYPE, TASK_LIST_MODEL
from llm_client import chat_completion
from prompts.get_tasks_list_adaptive_resource import SYSTEM_PROMPT


def _extract_first_json_object(text: str) -> dict:
    """Extract and parse the first JSON object from a string.

    Handles outputs like:
      { ...json... }\n\nKey reasoning: ...
    and optional ``` fences.
    """
    if not isinstance(text, str):
        raise ValueError("LLM output is not a string")

    s = text.strip()
    if not s:
        raise ValueError("LLM output is empty")

    # Strip markdown code fences if present
    if s.startswith("```"):
        s = s.split("\n", 1)[1] if "\n" in s else ""
        if "```" in s:
            s = s.rsplit("```", 1)[0].strip()

    # Find first object start
    start = s.find("{")
    if start == -1:
        raise ValueError("No JSON object start '{' found")

    decoder = json.JSONDecoder()
    obj, _end = decoder.raw_decode(s[start:])
    if not isinstance(obj, dict):
        raise ValueError("Top-level JSON value is not an object")
    return obj

# Paths
BASE_PATH = "data/"+DATA_TYPE+"/"
DATA_PATH = BASE_PATH+"sample_data.csv"
META_PATH = BASE_PATH+"metadata.json"
CONTEXT_PATH = BASE_PATH+"context.txt"
RESOURCE_SUMMARY_PATH = "resource_stat/resource_usage_summary.json"
OUTPUT_DIR = "generated_tasks/"+DATA_TYPE
TASK_LIST_PATH = OUTPUT_DIR+"/tasks_list.json"

# Read all inputs
with open(DATA_PATH, "r") as f:
    sample_data = f.read()

with open(META_PATH, "r") as f:
    metadata = json.load(f)

with open(CONTEXT_PATH, "r") as f:
    context = f.read()

# Ensure task list exists; if not create with empty tasks list
if not os.path.exists(TASK_LIST_PATH):
    os.makedirs(os.path.dirname(TASK_LIST_PATH), exist_ok=True)
    with open(TASK_LIST_PATH, "w", encoding="utf-8") as f:
        json.dump({"tasks": []}, f, indent=2)

with open(TASK_LIST_PATH, "r", encoding="utf-8") as f:
    existing_tasks = f.read()

with open(RESOURCE_SUMMARY_PATH, "r") as f:
    resource_summary = f.read()

system_prompt = Template(SYSTEM_PROMPT).substitute(DATA_TYPE=DATA_TYPE)
# User prompt with data, metadata, and context
user_prompt = f"""
Sample Data:
{sample_data}

Metadata:
{json.dumps(metadata, indent=2)}

Context:
{context}

Existing tasks and their descriptions:
{existing_tasks}

Summary of current resource usage and its availability on the edge device:
{resource_summary} 
"""

#print how many tasks are in existing_tasks
existing_tasks_json = json.loads(existing_tasks)
print(f"{len(existing_tasks_json['tasks'])} no. of existing tasks are sent to LLM.")

# Call the LLM
response = chat_completion(
    model=TASK_LIST_MODEL,
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]    
)

# Extract response content
with open("ResponseLLM.txt", 'w') as json_file:
    json.dump(response, json_file, indent=4)


exit()


raw_output = response.choices[0].message.content or ""

# Parse JSON safely (extract-first-json)
try:
    tasks_data = _extract_first_json_object(raw_output)
except Exception:
    print("The LLM response was not valid JSON. Saving raw output for review.")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(os.path.join(OUTPUT_DIR, "raw_output.txt"), "w", encoding="utf-8") as f:
        f.write(raw_output)
    exit()

# if no new tasks are generated, print the reason
if len(tasks_data.get("tasks", [])) == 0:
    reason = tasks_data.get("empty_reason", "No reason provided.")
    print("No new tasks were generated. Reason: " + reason)
    exit()

# print how many new tasks are generated
print(f"{len(tasks_data['tasks'])} new tasks are generated by LLM.")
# ensure each new task explicitly carries its DATA_TYPE for downstream modules
for t in tasks_data.get("tasks", []):
    t.setdefault("data_type", DATA_TYPE)

# Save new tasks for code generator (parity with adaptive orchestrator)
os.makedirs(OUTPUT_DIR, exist_ok=True)
with open(os.path.join(OUTPUT_DIR, "new_tasks.json"), "w", encoding="utf-8") as f:
    json.dump(tasks_data, f, indent=2)

# Merge with existing tasks_list.json
if os.path.exists(TASK_LIST_PATH):
    with open(TASK_LIST_PATH, "r", encoding="utf-8") as f:
        existing_tasks_data = json.load(f)
    existing_tasks_data["tasks"].extend(tasks_data["tasks"])
    tasks_data = existing_tasks_data

# Write updated tasks_list.json
with open(TASK_LIST_PATH, "w", encoding="utf-8") as f:
    json.dump(tasks_data, f, indent=2)
print("The list of all tasks with their description are successfully saved in "+TASK_LIST_PATH)

