"""
task_code_generator.py
-------------------
This module contains functions to generate Python task code
based on LLM responses for edge devices in an LLM-assisted edge computing system.

Task_list.json may contain multiple tasks, however, we will call multiple LLM calls to generate code for each task separately.
Each generated task code will be saved as a separate .py file in the `generated_tasks/{DATA_TYPE}` directory.

"""

import os
import json
import sys
import validator
from openai import OpenAI
from config import OPENAI_API_KEY, DATA_TYPE
from string import Template
from prompts.get_single_task_code import SYSTEM_PROMPT

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

# Initialize the LLM client
client = OpenAI(api_key=OPENAI_API_KEY)

# Paths = Data type specific
# Make sure that a folder name with following data type exists inside
#   data/, generated_tasks/ and output/ folders.
#
#### Select any one data type by uncommenting the line below
# DATA_TYPE = "temp_humidity" # it is expected that a folder with this name exists
# DATA_TYPE = "air_quality" # it is expected that a folder with this name exists

# Paths
BASE_PATH = "data/"+DATA_TYPE+"/"
DATA_PATH = BASE_PATH+"sample_data.csv"
META_PATH = BASE_PATH+"metadata.json"
CONTEXT_PATH = BASE_PATH+"context.txt"
OUTPUT_DIR = "generated_tasks/"+DATA_TYPE
TASK_LIST_PATH = OUTPUT_DIR+"/new_tasks.json" # path to new tasks generated by llm_orchestrator_adaptive.py
# NO_OF_TASKS = 2  # Number of tasks to generate code for at a time


def call_llm_for_task_code(task_list, error_message=None):
    system_prompt = Template(SYSTEM_PROMPT).substitute(DATA_TYPE=DATA_TYPE)

    if isinstance(task_list, dict):
        task_list_payload = json.dumps(task_list, ensure_ascii=False, indent=2)
    else:
        task_list_payload = str(task_list)

    feedback_section = ""
    if error_message:
        feedback_section = f"\n    Previous Validation Feedback:\n    {error_message}\n    "

    user_prompt = f"""
    Sample Data:
    {sample_data}

    Metadata:
    {json.dumps(metadata, indent=2)}

    Context:
    {context}

    Tasks List:
    {task_list_payload}
    {feedback_section}
    """

    response = client.chat.completions.create(
        model="gpt-5",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )
    raw_output = response.choices[0].message.content

    try:
        tasks_data = json.loads(raw_output)
    except json.JSONDecodeError:
        print("The LLM response was not valid JSON. Saving raw output for review.")
        print(raw_output)
        return None
    return tasks_data
    
    

def save_task_code(tasks_data, allowed_task_names=None):
    # # Save each generated task as a separate .py file
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for task in tasks_data["tasks"]:
        if allowed_task_names and task["task_name"] not in allowed_task_names:
            continue
        filename = f"{task['task_name']}.py"
        filepath = os.path.join(OUTPUT_DIR, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(task["code"])
        print(f" Saved: {filename}")
        print(f" Description: {task['description']}\n")

    print(f" All tasks generated successfully and saved in {OUTPUT_DIR} folder.")


# Read all inputs
with open(DATA_PATH, "r") as f:
    sample_data = f.read()

with open(META_PATH, "r") as f:
    metadata = json.load(f)

with open(CONTEXT_PATH, "r") as f:
    context = f.read()


with open(TASK_LIST_PATH, "r", encoding="utf-8") as f:
    tasks_payload = json.load(f)

pending_tasks = tasks_payload.get("tasks", [])


def update_task_status(task_name, status_message):
    for task_entry in tasks_payload.get("tasks", []):
        if task_entry.get("task_name") == task_name:
            task_entry["status"] = status_message
            break
    with open(TASK_LIST_PATH, "w", encoding="utf-8") as out_file:
        json.dump(tasks_payload, out_file, ensure_ascii=False, indent=2)


MAX_VALIDATION_ATTEMPTS = 2

for task_info in pending_tasks:
    base_task = {
        "task_name": task_info.get("task_name"),
        "description": task_info.get("description", ""),
    }

    if not base_task["task_name"]:
        print(f" Skipping task with missing name: {task_info}")
        continue

    # code to skip if the task code file already exists
    existing_task_path = os.path.join(OUTPUT_DIR, f"{base_task['task_name']}.py")
    if os.path.exists(existing_task_path):
        print(
            f"\nSkipping {base_task['task_name']} - existing script detected at {existing_task_path}."
        )
        update_task_status(base_task["task_name"], "code_generated")
        continue

    attempt = 0
    feedback = None
    task_generated_successfully = False

    while attempt < MAX_VALIDATION_ATTEMPTS:
        attempt += 1
        payload = {"tasks": [base_task]}

        generated_tasks = call_llm_for_task_code(payload, error_message=feedback)
        if not generated_tasks or not generated_tasks.get("tasks"):
            print(f" LLM failed to return code for {base_task['task_name']} (attempt {attempt}).")
            break

        validation_result = validator.call_llm_for_validator(generated_tasks)
        if not validation_result or not validation_result.get("tasks"):
            print(f" Validator did not return results for {base_task['task_name']} (attempt {attempt}).")
            break

        validation_entry = next(
            (item for item in validation_result["tasks"] if item.get("task_name") == base_task["task_name"]),
            None,
        )

        if not validation_entry:
            print(f" Validator response missing entry for {base_task['task_name']}.")
            break

        if validation_entry.get("is_valid"):
            save_task_code(generated_tasks, allowed_task_names={base_task["task_name"]})
            update_task_status(base_task["task_name"], "code_generated")
            task_generated_successfully = True
            break

        feedback = validation_entry.get("error_message") or "Validation failed without a message."
        print(
            f" Validation failed for {base_task['task_name']} on attempt {attempt}."
            f" Feedback: {feedback}"
        )

    if not task_generated_successfully:
        update_task_status(base_task["task_name"], "failed to generate correct code")
        print(f" Failed to generate valid code for {base_task['task_name']} after {MAX_VALIDATION_ATTEMPTS} attempts.")

    
    
